do not attempt to use __git_ps1 when it is not available

diff --git a/_bashrc_nmandery b/_bashrc_nmandery
--- a/_bashrc_nmandery
+++ b/_bashrc_nmandery
@@ -1,16 +1,21 @@
 # vi mode command line editing (enter VI mode using ESC)
 set -o vi
 
-export GIT_PS1_SHOWDIRTYSTATE=1
+if type "__git_ps1" &>/dev/null; then
+    export GIT_PS1_SHOWDIRTYSTATE=1
 
-# colored prompt
-# the git branch depends on bash_completion which should be sourced before. on debian
-# it is normally added to ~/.bashrc. Otherwise add
-# if [ -f /etc/bash_completion ]; then
-# . /etc/bash_completion
-# fi
-#           |------- user@host ------------|  |----- directory -----------| |---- nonzero returncodes -------| |--------- git branch ----------------|
-export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]: \[\033[01;34m\]\w\[\033[00m\] \[\033[01;31m\]${?##0}\[\033[00m\] \[\033[00;33m\]$(__git_ps1)\[\033[00m\]\n\$ '
+    # colored prompt
+    # the git branch depends on bash_completion which should be sourced before. on debian
+    # it is normally added to ~/.bashrc. Otherwise add
+    # if [ -f /etc/bash_completion ]; then
+    # . /etc/bash_completion
+    # fi
+    #           |------- user@host ------------|  |----- directory -----------| |---- nonzero returncodes -------| |--------- git branch ----------------|
+    export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]: \[\033[01;34m\]\w\[\033[00m\] \[\033[01;31m\]${?##0}\[\033[00m\] \[\033[00;33m\]$(__git_ps1)\[\033[00m\]\n\$ '
+else
+    #           |------- user@host ------------|  |----- directory -----------| |---- nonzero returncodes -------|
+    export PS1='\[\033[01;32m\]\u@\h\[\033[00m\]: \[\033[01;34m\]\w\[\033[00m\] \[\033[01;31m\]${?##0}\[\033[00m\]\n\$ '
+fi
 
 # disable visual bell. This setting should be placed in ~/.inputrc, calling bind with
 # the setting as parameter will also work
@@ -30,7 +35,7 @@ export SVN_EDITOR=$EDITOR
 # fix java swing guis in awesomewm
 # http://stackoverflow.com/questions/721215/how-can-i-fix-a-java-gui-program-swing-that-it-works-with-awesome-wm
 # requires "wmname" from suckless
-WMNAME=$(which wmname || echo "")
+WMNAME=$(which wmname 2>/dev/null || echo "")
 if [ "$WMNAME" != "" ]; then
     $WMNAME LG3D
 fi
